[workspace]
members = [
    "crates/entity",
    "crates/migration",
    "crates/server",
    "crates/health-check"
]

[package]
name = "lyonkit-api"
description = "Backend api for the lyonkit project"
version = "0.1.0"
authors = ["Léo Coletta <leo.coletta@pm.me>"]
edition = "2021"