[package]
name = "migration"
version = "0.1.0"
edition = "2021"
authors = ["Léo Coletta <leo.coletta@pm.me>"]
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
sea-orm-migration = { version = "0.8.3", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
chrono = "0.4.19"
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
tokio = { version = "1.19.2", features = ["macros"] }
