[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Léo Coletta <leo.coletta@pm.me>"]
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "lyonkit-api"

[dependencies]
entity = { path = "../entity" }
actix-web = "4.0.1"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread"] }
serde = "1.0.137"
tracing = "0.1.34"
tracing-actix-web = "0.5.1"
opentelemetry = { version = "0.17", features = ["rt-tokio-current-thread"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = { version = "0.17.2" }
tracing-subscriber = { version = "0.3.11", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.2"
tracing-log = "0.1.3"
sea-orm = { version = "0.8.0", features = ["debug-print", "runtime-tokio-rustls", "sqlx-postgres"]}
config = { version = "0.13.1" }
serde_json = "1.0.81"
chrono = "0.4.19"
futures = "0.3.21"
getset = "0.1.2"
uuid = { version = "0.8.2", features = ["serde"] }
derive_more = "0.99.17"
url = "2.2.2"
async-trait = "0.1.53"
once_cell = "1.12.0"

[dev-dependencies]
migration = { path = "../migration" }
portpicker = "0.1.1"
reqwest = { version = "0.11.10", features = ["__rustls", "json", "cookies"], default-features = false }
test-context = "0.1.3"
