[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Léo Coletta <leo.coletta@pm.me>"]
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "lyonkit-api"

[dependencies]
entity = { path = "../entity" }
migration = { path = "../migration" }
actix-web = "4.1.0"
actix-multipart = { version = "0.4.0" }
actix-cors = { version = "0.6.1" }
mime = { version = "0.3.16" }
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
serde = "1.0.137"
tracing = "0.1.35"
tracing-actix-web = { version = "0.5.1", features = ["default", "opentelemetry_0_17"] }
opentelemetry = { version = "0.17", features = ["rt-tokio-current-thread"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = { version = "0.17.3" }
tracing-subscriber = { version = "0.3.11", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.2"
tracing-log = "0.1.3"
sea-orm = { version = "0.8.0", features = ["debug-print", "runtime-tokio-native-tls", "sqlx-postgres"]}
config = { version = "0.13.1" }
serde_json = "1.0.81"
chrono = "0.4.19"
futures = "0.3.21"
getset = "0.1.2"
uuid = { version = "0.8.2", features = ["serde"] }
derive_more = "0.99.17"
url = "2.2.2"
async-trait = "0.1.56"
once_cell = "1.12.0"
aws-sdk-s3 = { version = "0.13.0", features = ["native-tls", "rt-tokio"], default-features = false }
aws-types = { version = "0.13.0" }
aws-config = { version = "0.13.0", features = ["native-tls", "rt-tokio"], default-features = false }
aws-smithy-http = { version = "0.43.0", features = ["rt-tokio"] }
aws-smithy-async = { version = "0.43.0", features = ["rt-tokio"] }
image = { version = "0.24.2" }
openssl = { version = "0.10.40", features = ["vendored"] }
openssl-probe = "0.1.5"
deunicode = { version = "1.3.1" }
lazy_static = { version = "1.4.0" }

[dev-dependencies]
portpicker = "0.1.1"
reqwest = { version = "0.11.11", features = ["json", "cookies", "multipart", "stream"], default-features = false }
test-context = "0.1.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.5.0"
